### PR TITLE
Fix active link highlighting

### LINKED ISSUE #89: react-router doesn't properly highlight the active link

### PR DESCRIPTION
**Pull request by stevenpetryk**
Closes #89.

### CODE REVIEW

File: src/components/NavigationContainer.js [hunk 1]
```diff
@@ -10,4 +10,4 @@ function mapStateToProps (state, ownProps) {
   }
 }
 
-export default connect(mapStateToProps)(Navigation)
+export default connect(mapStateToProps, null, null, { pure: false })(Navigation)
```
Comment (stevenpetryk) [inline src/components/NavigationContainer.js:13]: This is part of the reason I'm a fan of programming languages that force you to name your arguments.
